/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/health/live": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Check process liveness
         * @description Return without touching models, JSON, or background jobs.
         */
        readonly get: operations["get_liveness_api_health_live_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/health/ready": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Check appliance readiness
         * @description Check all local dependencies used to serve tablet traffic.
         */
        readonly get: operations["get_readiness_api_health_ready_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/anomaly/state": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get the latest personal state
         * @description Return the last evaluation without rerunning either model.
         */
        readonly get: operations["get_anomaly_state_api_v1_anomaly_state_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/guardian/login": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Guardian Login
         * @description Issue a guardian session cookie after plaintext JSON comparison.
         */
        readonly post: operations["guardian_login_api_v1_auth_guardian_login_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/guardian/logout": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Guardian Logout
         * @description Revoke the guardian cookie hash and expire the browser cookie.
         */
        readonly post: operations["guardian_logout_api_v1_auth_guardian_logout_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/guardian/session": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Guardian Session
         * @description Return current guardian session metadata.
         */
        readonly get: operations["guardian_session_api_v1_auth_guardian_session_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/tablet/logout": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Tablet Logout
         * @description Revoke the tablet cookie hash and expire the browser cookie.
         */
        readonly post: operations["tablet_logout_api_v1_auth_tablet_logout_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/tablet/pair": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Tablet Pair
         * @description Pair one tablet and revoke any prior tablet session.
         */
        readonly post: operations["tablet_pair_api_v1_auth_tablet_pair_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/tablet/session": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Tablet Session
         * @description Return current paired-tablet session metadata.
         */
        readonly get: operations["tablet_session_api_v1_auth_tablet_session_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/conversations/sessions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List conversation session summaries
         * @description Return metrics-only session history.
         */
        readonly get: operations["list_conversations_api_v1_conversations_sessions_get"];
        readonly put?: never;
        /**
         * Start a reminiscence conversation
         * @description Start a scheduled or voluntary session with a synthesizable question.
         */
        readonly post: operations["start_conversation_api_v1_conversations_sessions_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/conversations/sessions/{session_id}/complete": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Complete a conversation session
         * @description Finalize a session and return its metrics-only summary.
         */
        readonly post: operations["complete_conversation_api_v1_conversations_sessions__session_id__complete_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/conversations/sessions/{session_id}/turns": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Recognize and reduce one user turn
         * @description Use ASR transiently, then persist metrics without text or audio.
         */
        readonly post: operations["record_conversation_turn_api_v1_conversations_sessions__session_id__turns_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/conversations/suggestion": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get today's scheduled conversation suggestion
         * @description Offer a daily session without treating a dismissed offer as an anomaly.
         */
        readonly get: operations["get_conversation_suggestion_api_v1_conversations_suggestion_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/demo/conversations/sessions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Start a public demo reminiscence conversation
         * @description Start a scheduled or voluntary session with a synthesizable question.
         */
        readonly post: operations["start_conversation_api_v1_demo_conversations_sessions_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/demo/conversations/sessions/{session_id}/complete": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Complete a public demo conversation session
         * @description Finalize a session and return its metrics-only summary.
         */
        readonly post: operations["complete_conversation_api_v1_demo_conversations_sessions__session_id__complete_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/demo/conversations/sessions/{session_id}/turns": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Recognize and reduce one public demo turn
         * @description Use ASR transiently, then persist metrics without text or audio.
         */
        readonly post: operations["record_conversation_turn_api_v1_demo_conversations_sessions__session_id__turns_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/routines/current": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get active tablet routine prompts
         * @description Advance due transitions and return prompts the tablet should display.
         */
        readonly get: operations["get_current_routines_api_v1_routines_current_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/routines/history": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List persisted routine executions
         * @description Advance transitions and return routine history without prompt text.
         */
        readonly get: operations["get_routine_history_api_v1_routines_history_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/routines/{execution_id}/confirm": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Confirm a completed routine
         * @description Record the tablet button press using the trusted server time.
         */
        readonly post: operations["confirm_routine_api_v1_routines__execution_id__confirm_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tablet/state": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get integrated tablet home state
         * @description Advance due routines and return one coherent home payload.
         */
        readonly get: operations["get_tablet_state_api_v1_tablet_state_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tts/demo-speech": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Synthesize public demo speech
         * @description Use the production voice engine for dynamic demo conversation questions.
         */
        readonly post: operations["synthesize_demo_speech_api_v1_tts_demo_speech_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tts/speech": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Synthesize Korean speech with local Supertonic 3
         * @description Return a non-persisted WAV that the tablet can play immediately.
         */
        readonly post: operations["synthesize_speech_api_v1_tts_speech_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Check process liveness (legacy)
         * @deprecated
         * @description Keep the original probe path compatible during rollout.
         */
        readonly get: operations["get_legacy_health_health_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnomalyMode
         * @description Primary evaluation mode used for a domain.
         * @enum {string}
         */
        readonly AnomalyMode: "COLD_START" | "ISOLATION_FOREST" | "INSUFFICIENT_DATA";
        /**
         * AnomalyStatus
         * @description Current individual state.
         * @enum {string}
         */
        readonly AnomalyStatus: "NORMAL" | "ANOMALOUS";
        /**
         * AuthRole
         * @description Supported single-appliance browser roles.
         * @enum {string}
         */
        readonly AuthRole: "GUARDIAN" | "TABLET";
        /**
         * CompleteConversationRequest
         * @description Tablet-observed reason for finalizing a conversation.
         */
        readonly CompleteConversationRequest: {
            /** @default USER_FINISHED */
            readonly reason: components["schemas"]["ConversationCompletionReason"];
        };
        /**
         * ConversationCompletionReason
         * @description Why the tablet finalized an active conversation.
         * @enum {string}
         */
        readonly ConversationCompletionReason: "USER_FINISHED" | "INACTIVITY_TIMEOUT" | "MAX_DURATION" | "NAVIGATION";
        /**
         * ConversationSource
         * @description How the user entered a conversation session.
         * @enum {string}
         */
        readonly ConversationSource: "SCHEDULED" | "VOLUNTARY";
        /**
         * ConversationStatus
         * @description Lifecycle state for a conversation session.
         * @enum {string}
         */
        readonly ConversationStatus: "ACTIVE" | "COMPLETED";
        /**
         * ConversationSuggestionResponse
         * @description Daily suggestion state consumed by the tablet home screen.
         */
        readonly ConversationSuggestionResponse: {
            /** Display Text */
            readonly display_text: string | null;
            /**
             * Scheduled Time
             * Format: time
             */
            readonly scheduled_time: string;
            /** Spoken Text */
            readonly spoken_text: string | null;
            /** Start Label */
            readonly start_label: string | null;
            /** Suggested */
            readonly suggested: boolean;
        };
        /**
         * ConversationSummaryResponse
         * @description Persisted session aggregate without conversation text.
         */
        readonly ConversationSummaryResponse: {
            /** Average Turn Duration Seconds */
            readonly average_turn_duration_seconds: number | null;
            /** Average Utterance Chars */
            readonly average_utterance_chars: number | null;
            /** Completed At */
            readonly completed_at: string | null;
            readonly completion_reason: components["schemas"]["ConversationCompletionReason"] | null;
            /** No Response Count */
            readonly no_response_count: number;
            /** Session Id */
            readonly session_id: string;
            /**
             * Started At
             * Format: date-time
             */
            readonly started_at: string;
            readonly status: components["schemas"]["ConversationStatus"];
            /** Total Utterance Chars */
            readonly total_utterance_chars: number;
            /** User Turn Count */
            readonly user_turn_count: number;
        };
        /**
         * CurrentRoutinesResponse
         * @description Active routine prompts at the server's current time.
         */
        readonly CurrentRoutinesResponse: {
            /** Items */
            readonly items: readonly components["schemas"]["RoutinePromptResponse"][];
            /**
             * Server Time
             * Format: date-time
             */
            readonly server_time: string;
        };
        /**
         * DomainEvaluationResponse
         * @description One detector's explainable current state.
         */
        readonly DomainEvaluationResponse: {
            /** Feature Names */
            readonly feature_names: readonly string[];
            /** Isolation Forest Signal */
            readonly isolation_forest_signal: boolean;
            readonly mode: components["schemas"]["AnomalyMode"];
            /** Observation Key */
            readonly observation_key: string | null;
            /** Persistence Signal */
            readonly persistence_signal: boolean;
            /** Reasons */
            readonly reasons: readonly string[];
            /** Rule Based Signal */
            readonly rule_based_signal: boolean;
            /** Sample Count */
            readonly sample_count: number;
            /** Score */
            readonly score: number | null;
            /** Signal Count */
            readonly signal_count: number;
            readonly status: components["schemas"]["AnomalyStatus"];
        };
        /**
         * GuardianLoginRequest
         * @description Plaintext password accepted only over the production HTTPS origin.
         */
        readonly GuardianLoginRequest: {
            /** Password */
            readonly password: string;
        };
        /** HTTPValidationError */
        readonly HTTPValidationError: {
            /** Detail */
            readonly detail?: readonly components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description A successful process liveness response.
         */
        readonly HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            readonly status: "ok";
        };
        /**
         * PersonalStateResponse
         * @description Combined current state with separate domain details.
         */
        readonly PersonalStateResponse: {
            /** Became Anomalous */
            readonly became_anomalous: boolean;
            /** Consecutive Anomalous Evaluations */
            readonly consecutive_anomalous_evaluations: number;
            readonly conversation: components["schemas"]["DomainEvaluationResponse"];
            /**
             * Evaluated At
             * Format: date-time
             */
            readonly evaluated_at: string;
            readonly routine: components["schemas"]["DomainEvaluationResponse"];
            readonly status: components["schemas"]["AnomalyStatus"];
        };
        /**
         * PhotoMemoryResponse
         * @description Photo and family-provided context rendered by the tablet.
         */
        readonly PhotoMemoryResponse: {
            /** Description */
            readonly description: string;
            /** Event */
            readonly event: string;
            /** Id */
            readonly id: string;
            /** Image Base64 */
            readonly image_base64: string;
            /** Image Media Type */
            readonly image_media_type: string;
            /** Location */
            readonly location: string;
            /** People */
            readonly people: readonly string[];
        };
        /**
         * ReadinessResponse
         * @description Successful checks for every local runtime dependency.
         */
        readonly ReadinessResponse: {
            /** Checks */
            readonly checks: {
                readonly [key: string]: "ok";
            };
            /**
             * Status
             * @default ok
             * @constant
             */
            readonly status: "ok";
        };
        /**
         * RoutineCategory
         * @description Supported routine categories in the MVP.
         * @enum {string}
         */
        readonly RoutineCategory: "MEAL" | "MEDICATION";
        /**
         * RoutineExecutionResponse
         * @description Persisted result for one routine occurrence.
         */
        readonly RoutineExecutionResponse: {
            /** Closed At */
            readonly closed_at: string | null;
            /** Confirmation Delay Seconds */
            readonly confirmation_delay_seconds: number | null;
            /** Confirmed At */
            readonly confirmed_at: string | null;
            /** Execution Id */
            readonly execution_id: string;
            /** Name */
            readonly name: string;
            /** Reminder Count */
            readonly reminder_count: number;
            /** Routine Id */
            readonly routine_id: string;
            /**
             * Scheduled At
             * Format: date-time
             */
            readonly scheduled_at: string;
            readonly state: components["schemas"]["RoutineState"];
        };
        /**
         * RoutinePromptResponse
         * @description One active routine prompt rendered and spoken by the tablet.
         */
        readonly RoutinePromptResponse: {
            readonly category: components["schemas"]["RoutineCategory"];
            /** Confirm Label */
            readonly confirm_label: string;
            /** Display Text */
            readonly display_text: string;
            /** Execution Id */
            readonly execution_id: string;
            /** Name */
            readonly name: string;
            /** Reminder Count */
            readonly reminder_count: number;
            /** Routine Id */
            readonly routine_id: string;
            /**
             * Scheduled At
             * Format: date-time
             */
            readonly scheduled_at: string;
            /** Spoken Text */
            readonly spoken_text: string;
            readonly state: components["schemas"]["RoutineState"];
        };
        /**
         * RoutineState
         * @description Lifecycle states for one scheduled routine occurrence.
         * @enum {string}
         */
        readonly RoutineState: "REMINDING" | "CONFIRMED" | "NOT_ANSWERED";
        /**
         * SessionResponse
         * @description Non-sensitive current session metadata.
         */
        readonly SessionResponse: {
            /**
             * Expires At
             * Format: date-time
             */
            readonly expires_at: string;
            readonly role: components["schemas"]["AuthRole"];
        };
        /**
         * SpeechSynthesisRequest
         * @description Visible spoken_text to synthesize with the configured local voice.
         */
        readonly SpeechSynthesisRequest: {
            /** Text */
            readonly text: string;
        };
        /**
         * SpeechTextResponse
         * @description Supertonic 3 input contract coupled to visible text.
         */
        readonly SpeechTextResponse: {
            /** Display Text */
            readonly display_text: string;
            /** Spoken Text */
            readonly spoken_text: string;
        };
        /**
         * StartConversationRequest
         * @description How the tablet starts a session.
         */
        readonly StartConversationRequest: {
            /** Photo Id */
            readonly photo_id?: string | null;
            readonly source: components["schemas"]["ConversationSource"];
        };
        /**
         * StartConversationResponse
         * @description Session context and the first safe question.
         */
        readonly StartConversationResponse: {
            readonly photo: components["schemas"]["PhotoMemoryResponse"];
            readonly question: components["schemas"]["SpeechTextResponse"];
            /** Session Id */
            readonly session_id: string;
            readonly status: components["schemas"]["ConversationStatus"];
        };
        /**
         * TabletPairingRequest
         * @description One-time tablet pairing credential.
         */
        readonly TabletPairingRequest: {
            /** Pairing Code */
            readonly pairing_code: string;
        };
        /**
         * TabletStateResponse
         * @description Everything needed to render the next tablet home state.
         */
        readonly TabletStateResponse: {
            /** Active Conversation Session Id */
            readonly active_conversation_session_id: string | null;
            /** Active Routines */
            readonly active_routines: readonly components["schemas"]["RoutinePromptResponse"][];
            readonly conversation_suggestion: components["schemas"]["ConversationSuggestionResponse"];
            /** Photos */
            readonly photos: readonly components["schemas"]["PhotoMemoryResponse"][];
            /**
             * Server Time
             * Format: date-time
             */
            readonly server_time: string;
        };
        /**
         * TurnMetricResponse
         * @description Non-sensitive metrics produced from one audio turn.
         */
        readonly TurnMetricResponse: {
            /** Chars Per Second */
            readonly chars_per_second: number | null;
            readonly next_question: components["schemas"]["SpeechTextResponse"];
            /** No Response */
            readonly no_response: boolean;
            /** Speech Detected */
            readonly speech_detected: boolean | null;
            /** Turn Duration Seconds */
            readonly turn_duration_seconds: number;
            /** Turn Id */
            readonly turn_id: string;
            /** Utterance Chars */
            readonly utterance_chars: number;
        };
        /** ValidationError */
        readonly ValidationError: {
            /** Context */
            readonly ctx?: Record<string, never>;
            /** Input */
            readonly input?: unknown;
            /** Location */
            readonly loc: readonly (string | number)[];
            /** Message */
            readonly msg: string;
            /** Error Type */
            readonly type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly get_liveness_api_health_live_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readonly get_readiness_api_health_ready_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Not ready */
            readonly 503: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly get_anomaly_state_api_v1_anomaly_state_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PersonalStateResponse"];
                };
            };
        };
    };
    readonly guardian_login_api_v1_auth_guardian_login_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["GuardianLoginRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly guardian_logout_api_v1_auth_guardian_logout_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly guardian_session_api_v1_auth_guardian_session_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    readonly tablet_logout_api_v1_auth_tablet_logout_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly tablet_pair_api_v1_auth_tablet_pair_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["TabletPairingRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly tablet_session_api_v1_auth_tablet_session_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    readonly list_conversations_api_v1_conversations_sessions_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["ConversationSummaryResponse"][];
                };
            };
        };
    };
    readonly start_conversation_api_v1_conversations_sessions_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["StartConversationRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["StartConversationResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly complete_conversation_api_v1_conversations_sessions__session_id__complete_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly session_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: {
            readonly content: {
                readonly "application/json": components["schemas"]["CompleteConversationRequest"] | null;
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ConversationSummaryResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly record_conversation_turn_api_v1_conversations_sessions__session_id__turns_post: {
        readonly parameters: {
            readonly query: {
                readonly turn_duration_seconds: number;
                readonly has_speech: boolean;
            };
            readonly header: {
                readonly "X-Turn-ID": string;
            };
            readonly path: {
                readonly session_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "audio/wav": string;
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TurnMetricResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_conversation_suggestion_api_v1_conversations_suggestion_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ConversationSuggestionResponse"];
                };
            };
        };
    };
    readonly start_conversation_api_v1_demo_conversations_sessions_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["StartConversationRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["StartConversationResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly complete_conversation_api_v1_demo_conversations_sessions__session_id__complete_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly session_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: {
            readonly content: {
                readonly "application/json": components["schemas"]["CompleteConversationRequest"] | null;
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ConversationSummaryResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly record_conversation_turn_api_v1_demo_conversations_sessions__session_id__turns_post: {
        readonly parameters: {
            readonly query: {
                readonly turn_duration_seconds: number;
                readonly has_speech: boolean;
            };
            readonly header: {
                readonly "X-Turn-ID": string;
            };
            readonly path: {
                readonly session_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "audio/wav": string;
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TurnMetricResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_current_routines_api_v1_routines_current_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CurrentRoutinesResponse"];
                };
            };
        };
    };
    readonly get_routine_history_api_v1_routines_history_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["RoutineExecutionResponse"][];
                };
            };
        };
    };
    readonly confirm_routine_api_v1_routines__execution_id__confirm_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly execution_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["RoutineExecutionResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_tablet_state_api_v1_tablet_state_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TabletStateResponse"];
                };
            };
        };
    };
    readonly synthesize_demo_speech_api_v1_tts_demo_speech_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["SpeechSynthesisRequest"];
            };
        };
        readonly responses: {
            /** @description Supertonic 3 PCM WAV audio for the public demo */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "audio/wav": unknown;
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly synthesize_speech_api_v1_tts_speech_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["SpeechSynthesisRequest"];
            };
        };
        readonly responses: {
            /** @description Supertonic 3 PCM WAV audio */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "audio/wav": unknown;
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_legacy_health_health_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
