import type { components } from './schema.generated'

type Schema = components['schemas']

export type AnomalyMode = Schema['AnomalyMode']
export type AnomalyStatus = Schema['AnomalyStatus']
export type AuthRole = Schema['AuthRole']
export type CompleteConversationRequest = Schema['CompleteConversationRequest']
export type ConversationCompletionReason = Schema['ConversationCompletionReason']
export type ConversationSource = Schema['ConversationSource']
export type ConversationStatus = Schema['ConversationStatus']
export type ConversationSuggestion = Schema['ConversationSuggestionResponse']
export type ConversationSummary = Schema['ConversationSummaryResponse']
export type ConversationTurnResponse = Schema['TurnMetricResponse']
export type CurrentRoutinesResponse = Schema['CurrentRoutinesResponse']
export type DomainEvaluation = Schema['DomainEvaluationResponse']
export type GuardianLoginRequest = Schema['GuardianLoginRequest']
export type HealthResponse = Schema['HealthResponse']
export type PersonalState = Schema['PersonalStateResponse']
export type PhotoMemory = Schema['PhotoMemoryResponse']
export type ReadinessResponse = Schema['ReadinessResponse']
export type RoutineCategory = Schema['RoutineCategory']
export type RoutineExecution = Schema['RoutineExecutionResponse']
export type RoutinePrompt = Schema['RoutinePromptResponse']
export type RoutineState = Schema['RoutineState']
export type SessionResponse = Schema['SessionResponse']
export type SpeechSynthesisRequest = Schema['SpeechSynthesisRequest']
export type SpeechText = Schema['SpeechTextResponse']
export type StartConversationRequest = Schema['StartConversationRequest']
export type StartConversationResponse = Schema['StartConversationResponse']
export type TabletPairingRequest = Schema['TabletPairingRequest']
export type TabletStateResponse = Schema['TabletStateResponse']
